system:
  tfk:
    location_view:
      full:
        frontpage_tfk:
          template: tfktelemarkBundle:full:tfk_frontpage.html.twig
          match:
           Id\Content: 57
        frontpage:
          template: tfktelemarkBundle:full:frontpage.html.twig
          match:
           Identifier\ContentType: [frontpage]
        arkiv:
          controller: tfktelemarkBundle:Item:arkiv
          match:
            Id\Content: 58
        folder:
          template: tfktelemarkBundle:full:folder.html.twig
          match:
            Identifier\ContentType: [folder]
        article:
          template: tfktelemarkBundle:full:article.html.twig
          match:
           Identifier\ContentType: [article]
      line:
        article:
          template: tfktelemarkBundle:line:article.html.twig
          match:
            Identifier\ContentType: [article]
        folder:
          template: tfktelemarkBundle:line:folder.html.twig
          match:
            Identifier\ContentType: [folder]
        personprofil:
          template: tfktelemarkBundle:line:personprofil.html.twig
          match:
            Identifier\ContentType: [personprofil]
        linkbox:
          template: tfktelemarkBundle:line:linkbox.html.twig
          match:
            Identifier\ContentType: [linkbox]
        infobox:
          template: tfktelemarkBundle:line:infobox.html.twig
          match:
            Identifier\ContentType: [infobox]
        image_gallery_slide:
          template: tfktelemarkBundle:line:image_gallery_slide.html.twig
          match:
            Identifier\ContentType: [image_gallery_slide]
        tabboks:
          template: tfktelemarkBundle:line:tabboks.html.twig
          match:
            Identifier\ContentType: [tabboks]
        tabboks_tab:
          template: tfktelemarkBundle:line:tabboks_tab.html.twig
          match:
            Identifier\ContentType: [tabboks_tab]
        slide_container:
          template: tfktelemarkBundle:line:slide_container.html.twig
          match:
            Identifier\ContentType: [slide_container]
        slide:
          template: tfktelemarkBundle:line:slide.html.twig
          match:
            Identifier\ContentType: [slide]
      custom:
        image:
          template: tfktelemarkBundle:custom:image.html.twig
          match:
            Identifier\ContentType: [image]
    content_view:
      custom:
        image:
          template: tfktelemarkBundle:custom:image.html.twig
          match:
            Identifier\ContentType: [image]
      responsive:
        image:
          template: tfktelemarkBundle:responsive:image.html.twig
          match:
            Identifier\ContentType: [image]
      embed-inline:
        image:
          template: tfktelemarkBundle:embed-inline:image.html.twig
          match:
            Identifier\ContentType: [image]
        slide_container:
          template: tfktelemarkBundle:line:slide_container.html.twig
          match:
            Identifier\ContentType: [slide_container]
        image_gallery:
          template: tfktelemarkBundle:line:image_gallery.html.twig
          match:
            Identifier\ContentType: [image_gallery]
        article:
          template: tfktelemarkBundle:line:article.html.twig
          match:
            Identifier\ContentType: [article]
        folder:
          template: tfktelemarkBundle:line:folder.html.twig
          match:
            Identifier\ContentType: [folder]
        linkbox:
          template: tfktelemarkBundle:line:linkbox.html.twig
          match:
            Identifier\ContentType: [linkbox]
      line:
        kampanjecontainer:
          template: tfktelemarkBundle:line:slide_container.html.twig
          match:
            Identifier\ContentType: [kampanjecontainer]
        tabboks:
          template: tfktelemarkBundle:line:tabboks.html.twig
          match:
            Identifier\ContentType: [tabboks]
        article:
          template: tfktelemarkBundle:line:article.html.twig
          match:
            Identifier\ContentType: [article]
        folder:
          template: tfktelemarkBundle:line:folder.html.twig
          match:
            Identifier\ContentType: [folder]
        linkbox:
          template: tfktelemarkBundle:line:linkbox.html.twig
          match:
            Identifier\ContentType: [linkbox]
      list:
        article:
          template: tfktelemarkBundle:list:article.html.twig
          match:
            Identifier\ContentType: [article]