system:
  tfk:
    location_view:
      full:
        frontpage_tfk:
          template: tfktelemarkBundle:full:tfk_frontpage.html.twig
          match:
           Id\Content: 2
        frontpage:
          template: tfktelemarkBundle:full:frontpage.html.twig
          match:
           Identifier\ContentType: [frontpage]
        folder:
          controller: tfktelemarkBundle:Item:folder
          match:
            Identifier\ContentType: [folder]
        article:
          template: tfktelemarkBundle:full:article.html.twig
          match:
           Identifier\ContentType: [article]
      line:
        article:
          template: tfktelemarkBundle:line:article.html.twig
          match:
            Identifier\ContentType: [article]
        folder:
          template: tfktelemarkBundle:line:folder.html.twig
          match:
            Identifier\ContentType: [folder]
        personprofil:
          template: tfktelemarkBundle:line:personprofil.html.twig
          match:
            Identifier\ContentType: [personprofil]
        linkbox:
          template: tfktelemarkBundle:line:linkbox.html.twig
          match:
            Identifier\ContentType: [linkbox]
        infobox:
          template: tfktelemarkBundle:line:infobox.html.twig
          match:
            Identifier\ContentType: [infobox]
        tabboks:
          template: tfktelemarkBundle:line:tabboks.html.twig
          match:
            Identifier\ContentType: [tabboks]
        tabboks_tab:
          template: tfktelemarkBundle:line:tabboks_tab.html.twig
          match:
            Identifier\ContentType: [tabboks_tab]
      custom:
        image:
          template: tfktelemarkBundle:custom:image.html.twig
          match:
            Identifier\ContentType: [image]
    content_view:
      custom:
        image:
          template: tfktelemarkBundle:custom:image.html.twig
          match:
            Identifier\ContentType: [image]
      responsive:
        image:
          template: tfktelemarkBundle:responsive:image.html.twig
          match:
            Identifier\ContentType: [image]