system:
  tfk:
    location_view:
      full:
        frontpage:
          template: tfktelemarkBundle:full:frontpage.html.twig
          match:
           Identifier\ContentType: [frontpage]
        folder:
          #controller: "tfktelemarkBundle:Folder:showFolderList"
          template: "tfktelemarkBundle:full:folder.html.twig"
          match:
            Identifier\ContentType: [folder]
        article:
          template: tfktelemarkBundle:full:article.html.twig
          match:
           Identifier\ContentType: [article]
      aside:
        folder:
          template: "tfktelemarkBundle:aside:folder.html.twig"
          match:
            Identifier\ContentType: [folder]
      aside_sub:
        folder:
           controller: "tfktelemarkBundle:Folder:showFolderListAsideView"
           template: "tfktelemarkBundle:aside_sub:folder.html.twig"
           match:
             Identifier\ContentType: [folder]
      line:
        personprofil:
          template: tfktelemarkBundle:line:personprofil.html.twig
          match:
            Identifier\ContentType: [personprofil]
        linkbox:
          template: tfktelemarkBundle:line:linkbox.html.twig
          match:
            Identifier\ContentType: [linkbox]
      custom:
        image:
          template: tfktelemarkBundle:custom:image.html.twig
          match:
            Identifier\ContentType: [image]
    content_view:
      custom:
        image:
          template: tfktelemarkBundle:custom:image.html.twig
          match:
            Identifier\ContentType: [image]