system:
  tfk:
    location_view:
      full:
        frontpage:
          template: tfktelemarkBundle:full:frontpage.html.twig
          match:
           Identifier\ContentType: [frontpage]
        folder:
          template: "tfktelemarkBundle:full:folder.html.twig"
          match:
            Identifier\ContentType: [folder]
        folder_aktuelt:
          #controller: "tfktelemarkBundle:Item:arkiv"
          template: tfktelemarkBundle:full:folder_arkiv.html.twig
          match:
            Id\Content: 58
        article:
          template: tfktelemarkBundle:full:article.html.twig
          match:
           Identifier\ContentType: [article]
      aside:
        folder:
          template: "tfktelemarkBundle:aside:folder.html.twig"
          match:
            Identifier\ContentType: [folder]
      aside_sub:
        folder:
           controller: "tfktelemarkBundle:Folder:showFolderListAsideView"
           template: "tfktelemarkBundle:aside_sub:folder.html.twig"
           match:
             Identifier\ContentType: [folder]
      line:
        article:
          template: tfktelemarkBundle:line:article.html.twig
          match:
            Identifier\ContentType: [article]
        personprofil:
          template: tfktelemarkBundle:line:personprofil.html.twig
          match:
            Identifier\ContentType: [personprofil]
        linkbox:
          template: tfktelemarkBundle:line:linkbox.html.twig
          match:
            Identifier\ContentType: [linkbox]
        infobox:
          template: tfktelemarkBundle:line:infobox.html.twig
          match:
            Identifier\ContentType: [infobox]
        tabboks:
          template: tfktelemarkBundle:line:tabboks.html.twig
          match:
            Identifier\ContentType: [tabboks]
        tabboks_tab:
          template: tfktelemarkBundle:line:tabboks_tab.html.twig
          match:
            Identifier\ContentType: [tabboks_tab]
      custom:
        image:
          template: tfktelemarkBundle:custom:image.html.twig
          match:
            Identifier\ContentType: [image]
    content_view:
      custom:
        image:
          template: tfktelemarkBundle:custom:image.html.twig
          match:
            Identifier\ContentType: [image]
      responsive:
        image:
          template: tfktelemarkBundle:responsive:image.html.twig
          match:
            Identifier\ContentType: [image]