services:
#    tfktelemark.example:
#        class: tfk\telemarkBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    telemark.criteria_helper:
        class: %ezdemo.criteria_helper.class%
    telemark.search_helper:
        class: %ezdemo.search_helper.class%
        arguments:
            - @ezpublish.api.service.search
            - %ezdemo.search.list.limit%
    telemark.menu.builder:
        class: tfk\telemarkBundle\Menu\Builder
        arguments:
            - @knp_menu.factory
            - @ezpublish.api.service.search
            - @router
            - @ezpublish.config.resolver
            - @ezpublish.api.service.location
            - @ezpublish.translation_helper
            - @service_container
    telemark.menu.top:
        class: tfk\telemarkBundle\Menu\Builder
        factory_service: telemark.menu.builder
        factory_method: createTopMenu
        arguments: [ @request ]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: top} # The alias is what is used to retrieve the menu
